import random

nouns = [
    "Kuckuck § 3 Ziff. 1 lit. b",
    "Ärzteschaft § 5 Ziff. 3 lit. d",
    "Überlingen § 9 Ziff. 2",
    "Kautschuk § 3 Ziff. 1 lit. b",
    "Kunigunde § 3 Ziff. 1 lit. b",
    "Tribut § 3 Ziff. 1 lit. b",
    "Tunesien § 3 Ziff. 1 lit. b",
    "Erstling § 3 Ziff. 1 lit. b",
    "Selbstlaut § 3 Ziff. 1 lit. b",
    "Kiel § 3 Ziff. 1 lit. c",
    "Film § 3 Ziff. 1 lit. c",
    "Militär § 3 Ziff. 1 lit. c",
    "Spiel § 3 Ziff. 1 lit. c",
    "Beispiel § 3 Ziff. 1 lit. c",
    "Million § 3 Ziff. 1 lit. c",
    "Mühle § 3 Ziff. 1 lit. c",
    "Ilse § 3 Ziff. 1 lit. c",
    "i, das lateinische § 8 Ziff. 3 lit. c",
    "Ställe § 3 Ziff. 1 lit. c",
    "Pupille § 3 Ziff. 1 lit. c",
    "Jubiläum § 3 Ziff. 1 lit. c",
    "Stuhl § 3 Ziff. 1 lit. c",
    "Schulze § 3 Ziff. 1 lit. c",
    "Puls § 3 Ziff. 1 lit. c",
    "Ulrich § 3 Ziff. 1 lit. c",
    "Vulkan § 3 Ziff. 1 lit. c",
    "Sulfat § 3 Ziff. 1 lit. c",
    "Pauline § 3 Ziff. 1 lit. c",
    "Eule § 3 Ziff. 1 lit. c",
    "Tee § 3 Ziff. 2",
    "Leo § 3 Ziff. 2",
    "Zoologe § 3 Ziff. 2",
    "Lilie § 3 Ziff. 2",
    "Mai § 3 Ziff. 2",
    "Feier § 3 Ziff. 2",
    "Ja § 3 Ziff. 2",
    "Menü § 3 Ziff. 2",
    "Revuen § 3 Ziff. 2",
    "Palais § 3 Ziff. 2",
    "Europäer § 3 Ziff. 2",
    "Uhu § 3 Ziff. 2",
    "Duett § 3 Ziff. 2",
    "Bau § 3 Ziff. 2",
    "Gemäuer § 3 Ziff. 2",
    "Lyon § 3 Ziff. 2",
    "Beter § 4 Ziff. 1 lit. a",
    "Bieter § 4 Ziff. 1 lit. a",
    "Butter § 4 Ziff. 1 lit. a",
    "Rest § 4 Ziff. 1 lit. a",
    "Ampel § 4 Ziff. 1 lit. a",
    "Ähre § 3 Ziff. 1 lit. a",
    "Wimper § 4 Ziff. 1 lit. a",
    "Juli § 4 Ziff. 1 lit. a",
    "Schmerzen § 4 Ziff. 1 lit. a",
    "Dummheiten § 4 Ziff. 1 lit. a",
    "Wahrheitsliebe § 4 Ziff. 1 lit. a",
    "Bedingungen § 4 Ziff. 1 lit. a",
    "Botschafter § 4 Ziff. 1 lit. a",
    "Wirtschaftler § 4 Ziff. 1 lit. a",
    "Espresso § 4 Ziff. 1 lit. b",
    "Dessau § 4 Ziff. 1 lit. b",
    "Fassung § 4 Ziff. 1 lit. b",
    "Massierung § 4 Ziff. 1 lit. b",
    "Assistent § 4 Ziff. 1 lit. b",
    "Gewissheit § 4 Ziff. 1 lit. b",
    "Seele § 4 Ziff. 1 lit. c",
    "Silo § 4 Ziff. 1 lit. c",
    "Seile § 4 Ziff. 1 lit. c",
    "Säule § 4 Ziff. 1 lit. c",
    "Berieselung § 4 Ziff. 1 lit. c",
    "Faserung § 4 Ziff. 1 lit. c",
    "Lösung § 4 Ziff. 1 lit. c",
    "Risiko § 4 Ziff. 1 lit. c",
    "Basis § 4 Ziff. 1 lit. c",
    "Susanne § 4 Ziff. 1 lit. c",
    "Frisur § 4 Ziff. 1 lit. c",
    "Revision § 4 Ziff. 1 lit. c",
    "Krise § 4 Ziff. 1 lit. c",
    "Peso § 4 Ziff. 1 lit. c",
    "Asien § 4 Ziff. 1 lit. c",
    "Atem § 4 Ziff. 2",
    "Kern § 4 Ziff. 2",
    "Belieben § 4 Ziff. 2",
    "Szene § 4 Ziff. 2",
    "Feld § 4 Ziff. 2",
    "Helga § 4 Ziff. 2",
    "Hilfe § 4 Ziff. 2",
    "Nachnahme/Nachname § 4 Ziff. 2",
    "Henne § 4 Ziff. 2",
    "Wege § 4 Ziff. 3",
    "Hund § 4 Ziff. 3",
    "Xaver § 4 Ziff. 3",
    "Berechnungen § 4 Ziff. 3",
    "Speyer § 4 Ziff. 3",
    "Reichtum § 4 Ziff. 3",
    "Huhn § 4 Ziff. 3",
    "Volumen § 4 Ziff. 3",
    "Chlor § 4 Ziff. 4 lit. a",
    "Sylt § 4 Ziff. 4 lit. a",
    "Beryll § 4 Ziff. 4 lit. a",
    "Bad Ischl § 4 Ziff. 4 lit. a",
    "Splitter § 4 Ziff. 4 lit. a",
    "Athlet § 4 Ziff. 4 lit. a",
    "Clemens § 4 Ziff. 4 lit. a",
    "Wolgalied § 4 Ziff. 4 lit. a",
    "Krebs § 4 Ziff. 4 lit. b",
    "Johansson § 4 Ziff. 4 lit. b",
    "Spions, des § 4 Ziff. 4 lit. b",
    "Rentner § 4 Ziff. 5",
    "Weltmeer § 4 Ziff. 5",
    "Erhaltung § 4 Ziff. 5",
    "Nestchen § 4 Ziff. 5",
    "Westfalen § 4 Ziff. 5",
    "Peitsche § 4 Ziff. 5",
    "Oase § 4 Ziff. 6",
    "Österreich § 7 Ziff. 1",
    "Familie § 4 Ziff. 6",
    "Triumph § 4 Ziff. 6",
    "Meiereien § 4 Ziff. 6",
    "Wirtin § 4 Ziff. 6",
    "Weltall § 4 Ziff. 6",
    "Druck § 4 Ziff. 7",
    "Kehle § 4 Ziff. 7",
    "Gemälde § 4 Ziff. 7",
    "Verleger § 4 Ziff. 7",
    "Zone § 4 Ziff. 7",
    "Scheune § 4 Ziff. 7",
    "Friedrich § 4 Ziff. 7",
    "Soda § 4 Ziff. 7",
    "Mieder § 4 Ziff. 7",
    "Gedanke § 4 Ziff. 7",
    "Sudeten § 4 Ziff. 7",
    "Wohl § 4 Ziff. 7",
    "Paulus § 4 Ziff. 7",
    "Schulter § 4 Ziff. 7",
    "Weisung § 4 Ziff. 7",
    "Feind § 5 Ziff. 1",
    "Mainz § 5 Ziff. 1",
    "Schrey § 5 Ziff. 1",
    "Meyer § 5 Ziff. 1",
    "Nation § 5 Ziff. 1",
    "Spione, die § 5 Ziff. 1",
    "Pionier § 5 Ziff. 1",
    "Uhr, die § 5 Ziff. 1",
    "Natur § 5 Ziff. 1",
    "Ursache § 5 Ziff. 1",
    "Brandenburg § 5 Ziff. 1",
    "Allee, die § 5 Ziff. 2",
    "Antlitz § 5 Ziff. 2",
    "Anton § 5 Ziff. 2",
    "Auflage § 5 Ziff. 2",
    "Glückauf § 5 Ziff. 2",
    "Dasein § 5 Ziff. 2",
    "Des-Dur § 5 Ziff. 2",
    "Dr. Moser § 5 Ziff. 2",
    "Doktors, des § 5 Ziff. 2",
    "Doktoren, die § 5 Ziff. 2",
    "Doktrin § 5 Ziff. 2",
    "Doktorarbeit § 5 Ziff. 2",
    "Schwester § 5 Ziff. 2",
    "Erregung § 5 Ziff. 2",
    "Es-Dur § 5 Ziff. 2",
    "Georg § 5 Ziff. 2",
    "Gegenliebe § 5 Ziff. 2",
    "Gegend § 5 Ziff. 2",
    "Inhaber § 5 Ziff. 2",
    "Guthaben § 5 Ziff. 2",
    "Einheit § 5 Ziff. 2",
    "Herberge § 5 Ziff. 2",
    "Hintersten, die § 5 Ziff. 2",
    "Interesse § 5 Ziff. 2",
    "Inneres § 5 Ziff. 2",
    "Skonto § 5 Ziff. 2",
    "Missgeschick § 5 Ziff. 2",
    "Missetat § 5 Ziff. 2",
    "Mitte, die § 5 Ziff. 2",
    "Miete, die § 5 Ziff. 2",
    "Nichtstuer § 5 Ziff. 2",
    "Habenichts § 5 Ziff. 2",
    "Mannschaft § 5 Ziff. 2",
    "Sonderausgabe § 5 Ziff. 2",
    "Absonderung § 5 Ziff. 2",
    "Sonderheit, in § 5 Ziff. 2",
    "Quantum § 5 Ziff. 2",
    "Lesung § 5 Ziff. 2",
    "Verzinsung § 5 Ziff. 2",
    "Belebung § 5 Ziff. 2",
    "Rettung § 5 Ziff. 2",
    "Zahlung § 5 Ziff. 2",
    "Verzierung § 5 Ziff. 2",
    "Verzerrung § 5 Ziff. 2",
    "Werdegang § 5 Ziff. 2",
    "Wille, der § 5 Ziff. 2",
    "Einwilligung § 5 Ziff. 2",
    "Wolle, die § 5 Ziff. 2",
    "Gewordene, das § 5 Ziff. 2",
    "Würde, die § 5 Ziff. 2",
    "Gebet § 5 Ziff. 3 lit. a",
    "Zutritt § 5 Ziff. 3 lit. a",
    "Angestellter § 5 Ziff. 3 lit. b",
    "Nebengebäude § 5 Ziff. 3 lit. b",
    "Hintergedanke § 5 Ziff. 3 lit. b",
    "Gewerkschaft § 5 Ziff. 3 lit. d",
    "Hinterlassenschaft § 5 Ziff. 3 lit. d",
    "Eigenschaft § 5 Ziff. 3 lit. d",
    "Kundschaft § 5 Ziff. 3 lit. d",
    "Wissenschaftler § 5 Ziff. 3 lit. d",
    "Beamtenschaft § 5 Ziff. 3 lit. d",
    "Arbeiterschaft § 5 Ziff. 3 lit. d",
    "Meisterschaft § 5 Ziff. 3 lit. d",
    "Landschaftsgestaltung § 5 Ziff. 3 lit. d",
    "Unüberlegtheit § 5 Ziff. 3 lit. e",
    "Zartheit § 5 Ziff. 3 lit. e",
    "Beliebtheit § 5 Ziff. 3 lit. e",
    "Buntheit § 5 Ziff. 3 lit. e",
    "Gescheitheit § 5 Ziff. 3 lit. e",
    "Verwandtschaft § 5 Ziff. 3 lit. e",
    "Wirtschaft § 5 Ziff. 3 lit. e",
    "Bereitschaft § 5 Ziff. 3 lit. e",
    "Schrifttum § 5 Ziff. 3 lit. e",
    "Papsttum § 5 Ziff. 3 lit. e",
    "Beobachtung § 6 Ziff. 1",
    "Beamter § 6 Ziff. 1",
    "Bearbeitung § 6 Ziff. 1",
    "Reorganisation § 6 Ziff. 1",
    "Alter § 6 Ziff. 2",
    "Weitesten, am § 6 Ziff. 2",
    "Erheiterung § 6 Ziff. 2",
    "AG § 6 Ziff. 3",
    "BGB § 6 Ziff. 3",
    "DGB § 6 Ziff. 3",
    "DM § 6 Ziff. 3",
    "Febr. § 6 Ziff. 3",
    "Aug. § 6 Ziff. 3",
    "Dez. § 6 Ziff. 3",
    "Fa. § 6 Ziff. 3",
    "GmbH § 6 Ziff. 3",
    "Dr. med. § 6 Ziff. 3",
    "PKW § 6 Ziff. 3",
    "PS § 6 Ziff. 3",
    "Prof. § 6 Ziff. 3",
    "Sek. § 6 Ziff. 3",
    "St. Pölten § 6 Ziff. 3",
    "UNO § 6 Ziff. 3",
    "USA § 6 Ziff. 3",
    "Brennnessel § 7 Ziff. 1",
    "Fräulein § 7 Ziff. 1",
    "Frühling § 7 Ziff. 1",
    "Neugierde § 7 Ziff. 1",
    "Rückgrat § 7 Ziff. 1",
    "Apfelsine § 7 Ziff. 1",
    "Abenteuer § 7 Ziff. 1",
    "Leumund § 7 Ziff. 1",
    "Scheusal § 7 Ziff. 1",
    "Brotgetreide § 7 Ziff. 1",
    "Baugerüst § 7 Ziff. 1",
    "Machtzuwachs § 7 Ziff. 1",
    "Hubraum § 7 Ziff. 1",
    "Erdrücken § 7 Ziff. 1",
    "Angabe § 7 Ziff. 1",
    "Angel § 7 Ziff. 1",
    "Bahndamm § 7 Ziff. 1",
    "Band § 7 Ziff. 1",
    "Kochtopf § 7 Ziff. 1",
    "Waschmaschine § 7 Ziff. 1",
    "Strohhülle § 7 Ziff. 1",
    "Nulllinie § 7 Ziff. 1",
    "Schnelläufer § 7 Ziff. 1",
    "Fahrrad § 7 Ziff. 1",
    "Sperrriegel § 7 Ziff. 1",
    "Jawort § 7 Ziff. 1",
    "Malmöbesucher § 7 Ziff. 1",
    "Revuestar § 7 Ziff. 1",
    "Sämaschine § 7 Ziff. 1",
    "U-Bahn § 7 Ziff. 1",
    "Baumeister § 7 Ziff. 1",
    "Rauheit § 7 Ziff. 1",
    "Neuzeit § 7 Ziff. 1",
    "Bräustübchen § 7 Ziff. 1",
    "Trübsal § 7 Ziff. 2",
    "Rätsel § 7 Ziff. 2",
    "Ersatz § 7 Ziff. 2",
    "Lehrsatz § 7 Ziff. 2",
    "Ansatz § 7 Ziff. 2",
    "Gegensatz § 7 Ziff. 2",
    "Drahtseil § 7 Ziff. 2",
    "Lohnsumme § 7 Ziff. 2",
    "Baus, des § 7 Ziff. 3",
    "Amerikas § 7 Ziff. 3",
    "Rehs, des § 7 Ziff. 3",
    "Treuste, der § 7 Ziff. 3",
    "Treueste, der § 7 Ziff. 3",
    "Entlassung § 7 Ziff. 4",
    "Bauleitung § 7 Ziff. 4",
    "Rohleder § 7 Ziff. 4",
    "Buchladen § 7 Ziff. 4",
    "Schlagloch § 7 Ziff. 4",
    "Notlage § 7 Ziff. 4",
    "Herzleiden § 7 Ziff. 4",
    "Deutschland § 7 Ziff. 4",
    "Festredner § 7 Ziff. 5",
    "Festpreis § 7 Ziff. 5",
    "Wirtschaftslage § 7 Ziff. 5",
    "Wirtschaftsbericht § 7 Ziff. 5",
    "Freigrenze § 7 Ziff. 5",
    "Friedensvertrag § 7 Ziff. 5",
    "Kraftakt § 7 Ziff. 5",
    "Leinöl § 7 Ziff. 5",
    "Reitschule § 7 Ziff. 5",
    "Stadtmitte § 7 Ziff. 5",
    "Wertpapier § 7 Ziff. 5",
    "Prokonsul § 7 Ziff. 5",
    "Vorort § 7 Ziff. 5",
    "Zwischenakt § 7 Ziff. 5",
    "Subjekt § 7 Ziff. 6",
    "Umlage § 7 Ziff. 6",
    "Hintergründe § 7 Ziff. 6",
    "Eisenbahn § 7 Ziff. 6",
    "Betriebsbesichtigung § 7 Ziff. 6",
    "Filmstudio § 7 Ziff. 6",
    "Trinkwasser § 7 Ziff. 6",
    "Eigenheimfinanzierung § 7 Ziff. 6",
    "Fußgänger § 7 Ziff. 6",
    "Fundbüro § 7 Ziff. 6",
    "Zuckerkrankheit § 7 Ziff. 6",
    "Tierkunde § 7 Ziff. 6",
    "Triebkraft § 7 Ziff. 6",
    "Blutegel § 7 Ziff. 6",
    "Feierabend § 7 Ziff. 6",
    "Südafrika § 7 Ziff. 6",
    "Lesart § 7 Ziff. 6",
    "Ananaseis § 7 Ziff. 6",
    "Gutachten § 7 Ziff. 6",
    "Schulamt § 7 Ziff. 6",
    "Hausapotheke § 7 Ziff. 6",
    "Grundirrtum § 7 Ziff. 6",
    "Grundübel § 7 Ziff. 6",
    "Hinterachse § 7 Ziff. 6",
    "Seemann § 7 Ziff. 7",
    "Ehevertrag § 7 Ziff. 7",
    "Roheit § 7 Ziff. 7",
    "Autobahn § 7 Ziff. 7",
    "Nettopreis § 7 Ziff. 7",
    "Kniebeuge § 7 Ziff. 7",
    "Zwischenspalt § 7 Ziff. 7",
    "Beitrag § 7 Ziff. 7",
    "Freiheit § 7 Ziff. 7",
    "Freikarte § 7 Ziff. 7",
    "Mainacht § 7 Ziff. 7",
    "Kältewelle § 7 Ziff. 7",
    "Härtegrad § 7 Ziff. 7",
    "Liegestuhl § 7 Ziff. 7",
    "Zeigefinger § 7 Ziff. 7",
    "Ruhelage § 7 Ziff. 7",
    "Ruhestand § 7 Ziff. 7",
    "Gummimantel § 7 Ziff. 7",
    "Giroüberweisung § 7 Ziff. 7",
    "Pflegeeltern § 7 Ziff. 7",
    "Seeufer § 7 Ziff. 7",
    "Fotoalbum § 7 Ziff. 7",
    "Regieanweisung § 7 Ziff. 7",
    "Beere § 8 Ziff. 1",
    "Boot § 8 Ziff. 1",
    "Saal § 8 Ziff. 1",
    "Waagenfabrik § 8 Ziff. 1",
    "Knie § 8 Ziff. 1",
    "Wiese § 8 Ziff. 1",
    "Fahrbahn § 8 Ziff. 1",
    "Reh § 8 Ziff. 1",
    "Rohling § 8 Ziff. 1",
    "Ebbe § 8 Ziff. 2",
    "Laubbaum § 8 Ziff. 2",
    "Erschaffung § 8 Ziff. 2",
    "Schaffell § 8 Ziff. 2",
    "Sonne § 8 Ziff. 2",
    "Stück § 8 Ziff. 2",
    "Mekka § 8 Ziff. 3 lit. a",
    "Strohhütte § 8 Ziff. 3 lit. a",
    "Nizza § 8 Ziff. 3 lit. a",
    "Haißler § 8 Ziff. 3 lit. b",
    "Waise § 8 Ziff. 3 lit. b",
    "Hain § 8 Ziff. 3 lit. b",
    "Saite § 8 Ziff. 3 lit. b",
    "Lecocq § 8 Ziff. 3 lit. b",
    "Bäckler § 8 Ziff. 3 lit. b",
    "Mantzel § 8 Ziff. 3 lit. b",
    "A § 8 Ziff. 3 lit. d",
    "Klasse B § 8 Ziff. 3 lit. d",
    "Englische Garten, der § 8 Ziff. 3 lit. d",
    "Armee § 8 Ziff. 3 lit. e",
    "Maße § 8 Ziff. 3 lit. e",
    "Masse § 8 Ziff. 3 lit. e",
    "Tenor § 8 Ziff. 3 lit. e",
    "Röntgen § 8 Ziff. 3 lit. f",
    "Börßum § 8 Ziff. 3 lit. f",
    "Leibniz' Schriften § 8 Ziff. 3 lit. f",
    "Haftende § 8 Ziff. 4",
    "Ahle § 8 Ziff. 4",
    "Aachen § 9 Ziff. 1",
    "Bayern § 9 Ziff. 1",
    "Blamage § 9 Ziff. 1",
    "Bordeaux § 9 Ziff. 1",
    "Branche § 9 Ziff. 1",
    "Cäsar § 9 Ziff. 1",
    "Charlotte § 9 Ziff. 1",
    "Chaussee § 9 Ziff. 1",
    "Christine § 9 Ziff. 1",
    "Clown § 9 Ziff. 1",
    "Coburg § 9 Ziff. 1",
    "Commonwealth § 9 Ziff. 1",
    "Csardas § 9 Ziff. 1",
    "Detail § 9 Ziff. 1",
    "Duisburg § 9 Ziff. 1",
    "Feuilleton § 9 Ziff. 1",
    "Ingenieur § 9 Ziff. 1",
    "Lyrik § 9 Ziff. 1",
    "Manager § 9 Ziff. 1",
    "Philipp § 9 Ziff. 1",
    "Plädoyer § 9 Ziff. 1",
    "Restaurant § 9 Ziff. 1",
    "Training § 9 Ziff. 1",
    "Zylinder § 9 Ziff. 1",
    "Sekretärin § 9 Ziff. 1",
    "Brabbée § 9 Ziff. 1",
    "Goethe § 9 Ziff. 1",
    "Haase § 9 Ziff. 1",
    "Haferkamp § 9 Ziff. 1",
    "Haverkamp § 9 Ziff. 1",
    "Kempff § 9 Ziff. 1",
    "Kemmpf § 9 Ziff. 1",
    "Kühn § 9 Ziff. 1",
    "Levasseur § 9 Ziff. 1",
    "Reinner § 9 Ziff. 1",
    "Reitter § 9 Ziff. 1",
    "Shakespeare § 9 Ziff. 1",
    "Andermatt § 9 Ziff. 2",
    "Eschweiler § 9 Ziff. 2",
    "Antenne § 9 Ziff. 2",
    "Antillen § 9 Ziff. 2",
    "Antiquariat § 9 Ziff. 2",
    "Anthrazit § 9 Ziff. 2",
    "Antwerpen § 9 Ziff. 2",
    "Enthusiasmus § 9 Ziff. 2",
    "Konnex § 9 Ziff. 2",
    "Konrad § 9 Ziff. 2",
    "Missionar § 9 Ziff. 2",
    "Mississippi § 9 Ziff. 2",
    "Zertifikat § 9 Ziff. 2",
    "Universalität § 9 Ziff. 2",
    "Veranda § 9 Ziff. 2",
    "Bad Wildungen § 9 Ziff. 2",
    "Australien § 9 Ziff. 3",
    "Distrikt § 9 Ziff. 3",
    "Industrieller § 9 Ziff. 3",
    "Aktie § 9 Ziff. 3",
    "Aktivität § 9 Ziff. 3",
    "Artikel § 9 Ziff. 3",
    "Attentäter § 9 Ziff. 3",
    "Phantast § 9 Ziff. 3",
    "Kartoffel § 9 Ziff. 3",
    "Martin § 9 Ziff. 3",
    "Montage § 9 Ziff. 3",
    "Optiker § 9 Ziff. 3",
    "Partisan § 9 Ziff. 3",
    "Porto § 9 Ziff. 3",
    "Produktion § 9 Ziff. 3",
    "Repräsentation § 9 Ziff. 3",
    "Sektor § 9 Ziff. 3",
    "Sekt § 9 Ziff. 3",
    "Sekte § 9 Ziff. 3",
    "Sekten § 9 Ziff. 3",
    "Gertrud § 9 Ziff. 3",
    "Zentralismus § 9 Ziff. 3",
    "Zeichnerin § 2 Ziff. 3",
    "Wiener § 2 Ziff. 3",
    "Zigeuner § 2 Ziff. 3",
    "Taunus § 2 Ziff. 3",
    "Mehl § 2 Ziff. 4",
    "Gas § 2 Ziff. 4",
    "Tat § 2 Ziff. 5",
    "Mitteilung § 2 Ziff. 5",
    "Mut § 2 Ziff. 5",
    "Furt § 2 Ziff. 5",
    "Landesteil § 2 Ziff. 6",
    "Strafe § 2 Ziff. 6",
    "Anstrengung § 2 Ziff. 6",
    "Männer § 3 Ziff. 1 lit. a",
    "Folge § 3 Ziff. 1 lit. a",
    "Aquarell § 3 Ziff. 1 lit. a",
    "Attrappe § 3 Ziff. 1 lit. a",
    "Kaschmir § 3 Ziff. 1 lit. a",
    "Max § 3 Ziff. 1 lit. a",
    "Kind § 3 Ziff. 1 lit. a",
    "Fleisch § 3 Ziff. 1 lit. a",
    "Kaiser § 3 Ziff. 1 lit. a",
    "Ehre § 3 Ziff. 1 lit. a",
    "Gäste § 3 Ziff. 1 lit. a",
    "Geste § 3 Ziff. 1 lit. a",
    "Cäcilie § 3 Ziff. 1 lit. a",
    "Qualtität § 3 Ziff. 1 lit. a",
    "Länder § 3 Ziff. 1 lit. a",
    "Präsident § 3 Ziff. 1 lit. a",
    "Kreuz § 3 Ziff. 1 lit. a",
    "Maurer § 3 Ziff. 1 lit. a",
    "Prinzip § 3 Ziff. 1 lit. b",
]

verbs = [
    "nehmen § 2 Ziff. 3",
    "dienen § 2 Ziff. 3",
    "winken § 2 Ziff. 3",
    "treten § 2 Ziff. 5",
    "bestehen § 2 Ziff. 6",
    "rechnen § 3 Ziff. 1 lit. a",
    "fördern § 3 Ziff. 1 lit. a",
    "wären § 3 Ziff. 1 lit. a",
    "wehren § 3 Ziff. 1 lit. a",
    "dirigieren § 3 Ziff. 1 lit. b",
    "titulieren § 3 Ziff. 1 lit. c",
    "regulieren § 3 Ziff. 1 lit. c",
    "annullieren § 3 Ziff. 1 lit. c",
    "dulden § 4 Ziff. 1 lit. a",
    "stutzen § 4 Ziff. 1 lit. a",
    "senken § 4 Ziff. 1 lit. c",
    "sinken § 4 Ziff. 1 lit. c",
    "gesunken § 4 Ziff. 1 lit. c",
    "rasieren § 4 Ziff. 1 lit. c",
    "säen § 4 Ziff. 1 lit. c",
    "atmen § 4 Ziff. 2",
    "kehren § 4 Ziff. 2",
    "blieben § 4 Ziff. 2",
    "setzen § 4 Ziff. 2",
    "hernehmen § 4 Ziff. 2",
    "halten § 4 Ziff. 3",
    "wurden § 4 Ziff. 3",
    "schieben § 4 Ziff. 7",
    "schwingen § 4 Ziff. 7",
    "häufen § 4 Ziff. 7",
    "hüpfen § 4 Ziff. 7",
    "suspendieren § 4 Ziff. 7",
    "entnehmen § 4 Ziff. 7",
    "murren § 5 Ziff. 1",
    "umändern § 5 Ziff. 2",
    "darreichen § 5 Ziff. 2",
    "dehnen § 5 Ziff. 2",
    "verdeutschen § 5 Ziff. 2",
    "entlassen § 5 Ziff. 2",
    "ersuchen § 5 Ziff. 2",
    "innehaben § 5 Ziff. 2",
    "verhaften § 5 Ziff. 2",
    "erheitern § 5 Ziff. 2",
    "herlaufen § 5 Ziff. 2",
    "erniedrigen § 5 Ziff. 2",
    "schonen, sich § 5 Ziff. 2",
    "seien § 5 Ziff. 2",
    "absondern § 5 Ziff. 2",
    "bevollmächtigen § 5 Ziff. 2",
    "werden, wir § 5 Ziff. 2",
    "dazwischenlegen § 5 Ziff. 2",
    "beunruhigen § 5 Ziff. 3 lit. b",
    "nachzuahmen § 5 Ziff. 3 lit. c",
    "beizutreten § 5 Ziff. 3 lit. c",
    "umzuwerfen § 5 Ziff. 3 lit. c",
    "zuzuziehen § 5 Ziff. 3 lit. c",
    "loszuwerden § 5 Ziff. 3 lit. c",
    "festzulegen § 5 Ziff. 3 lit. c",
    "beerben § 6 Ziff. 1",
    "beabsichtigen § 6 Ziff. 1",
    "hintansetzen § 6 Ziff. 1",
    "zueignen § 6 Ziff. 1",
    "herbeieilen § 6 Ziff. 1",
    "beiordnen § 6 Ziff. 1",
    "spalten § 6 Ziff. 2",
    "kennenzulernen § 7 Ziff. 1",
    "erdrücken § 7 Ziff. 1",
    "weissagen § 7 Ziff. 1",
    "reiht sich ein, er § 7 Ziff. 3",
    "darauflegen § 7 Ziff. 4",
    "zuzulassen § 7 Ziff. 4",
    "beehren § 7 Ziff. 5",
    "durchüben § 7 Ziff. 5",
    "hereilen § 7 Ziff. 5",
    "herbeiströmen § 7 Ziff. 5",
    "verewigen § 7 Ziff. 5",
    "umherfahren § 7 Ziff. 6",
    "umzukehren § 7 Ziff. 6",
    "maßhalten § 7 Ziff. 6",
    "umordnen § 7 Ziff. 6",
    "umarbeiten § 7 Ziff. 6",
    "stehlen § 8 Ziff. 1",
    "sehen § 8 Ziff. 1",
    "wissen § 8 Ziff. 2",
    "fahnden § 8 Ziff. 3 lit. e",
    "fanden § 8 Ziff. 3 lit. e",
    "selbst Kritik üben § 8 Ziff. 3 lit. g",
    "kann ich's § 8 Ziff. 4",
    "vernichten § 8 Ziff. 4",
    "diktieren § 9 Ziff. 3",
    "filtrieren § 9 Ziff. 3",
    "riet § 2 Ziff. 5",
    "lebet § 2 Ziff. 5",
    "lebt § 2 Ziff. 5",
    "verwirklicht § 2 Ziff. 5",
    "schimpfst § 4 Ziff. 4 lit. b",
    "gezwickt § 4 Ziff. 7",
    "vermisst § 5 Ziff. 2",
    "berücksichtigt § 5 Ziff. 2",
    "erübrigt § 5 Ziff. 2",
    "wurdet § 5 Ziff. 2",
    "würdet § 5 Ziff. 2",
    "bewirtet § 6 Ziff. 2",
    "hältst, du § 7 Ziff. 2",
    "spürst, du § 7 Ziff. 2",
    "geht § 7 Ziff. 3",
    "kniet § 7 Ziff. 3",
    "bemüht § 7 Ziff. 3",
    "mäht § 7 Ziff. 3",
    "schaut § 7 Ziff. 3",
    "lacht § 7 Ziff. 3",
    "leihst § 7 Ziff. 3",
    "säst, du § 7 Ziff. 3",
    "sähest, du § 7 Ziff. 3",
    "kostümiert § 9 Ziff. 3",
    "fände § 3 Ziff. 1 lit. a",
    "gäbe § 3 Ziff. 1 lit. a",
    "gebe § 3 Ziff. 1 lit. a",
    "wusste § 4 Ziff. 1 lit. b",
    "heule § 4 Ziff. 3",
    "ermanne dich § 8 Ziff. 3 lit. a",
    "rief § 4 Ziff. 7",
    "da, er ist § 5 Ziff. 2",
    "sind's, sie § 5 Ziff. 2",
    "wird's § 5 Ziff. 2",
    "das ist's § 8 Ziff. 4",
    "Fahren Sie? § 8 Ziff. 3 lit. d",
    "Hat er's? § 5 Ziff. 2",
    "Selbstkritik üben § 8 Ziff. 3 lit. g",
]

# pradvectives contains prepositions, adverbs and adjectives.
pradvectives = [
    "minus § 2 Ziff. 3",
    "abstrakt § 9 Ziff. 3",
    "unt're § 8 Ziff. 3 lit. f",
    "somit § 7 Ziff. 8",
    "lichtecht § 7 Ziff. 6",
    "zerlumpt § 7 Ziff. 4",
    "erneut § 7 Ziff. 3",
    "tiefgekühlt § 7 Ziff. 1",
    "zuinnerst § 6 Ziff. 1",
    "uninteressant § 6 Ziff. 1",
    "geulkt § 6 Ziff. 1",
    "geehrt § 6 Ziff. 1",
    "zugeknöpft § 5 Ziff. 3 lit. b",
    "umgekehrt § 5 Ziff. 3 lit. b",
    "insgesamt § 5 Ziff. 3 lit. b",
    "beigefügt § 5 Ziff. 3 lit. b",
    "zuoberst § 5 Ziff. 3 lit. a",
    "zuletzt § 5 Ziff. 3 lit. a",
    "unlängst § 5 Ziff. 3 lit. a",
    "unecht § 5 Ziff. 3 lit. a",
    "geeitert § 5 Ziff. 3 lit. a",
    "geeignet § 5 Ziff. 3 lit. a",
    "geölt § 5 Ziff. 3 lit. a",
    "gelegt § 5 Ziff. 3 lit. a",
    "geachtet § 5 Ziff. 3 lit. a",
    "gequält § 5 Ziff. 3 lit. a",
    "gewollt § 5 Ziff. 2",
    "gewillt § 5 Ziff. 2",
    "zuvörderst § 5 Ziff. 2",
    "gesondert § 5 Ziff. 2",
    "gesollt § 5 Ziff. 2",
    "geschafft § 5 Ziff. 2",
    "ernsthaftest § 5 Ziff. 2",
    "habhaft § 5 Ziff. 2",
    "gehabt § 5 Ziff. 2",
    "geordnet § 5 Ziff. 2",
    "dergestalt § 5 Ziff. 2",
    "verausgabt § 5 Ziff. 2",
    "alliiert § 5 Ziff. 2",
    "weit § 5 Ziff. 1",
    "sooft § 4 Ziff. 6",
    "mondän § 9 Ziff. 1",
    "drin § 8 Ziff. 4",
    "ohn' Unterlass § 8 Ziff. 3 lit. f",
    "innen, von § 8 Ziff. 3 lit. a",
    "soeben § 7 Ziff. 8",
    "dermaßen § 7 Ziff. 8",
    "währenddessen § 7 Ziff. 8",
    "liebsten, am § 7 Ziff. 2",
    "geeignetsten, am § 7 Ziff. 2",
    "uneben § 6 Ziff. 1",
    "zugenommen § 5 Ziff. 3 lit. a",
    "hinzugezogen § 5 Ziff. 3 lit. b",
    "ununterbrochen § 5 Ziff. 3 lit. a",
    "sodann § 5 Ziff. 2",
    "obschon § 5 Ziff. 2",
    "hin § 5 Ziff. 2",
    "heran § 5 Ziff. 2",
    "hinnen, von § 5 Ziff. 2",
    "hinten, von § 5 Ziff. 2",
    "fürderhin § 5 Ziff. 2",
    "diejenigen § 5 Ziff. 2",
    "seinen § 5 Ziff. 2",
    "seinetwegen § 5 Ziff. 2",
    "dergleichen § 5 Ziff. 2",
    "indessen § 5 Ziff. 2",
    "infolgedessen § 5 Ziff. 2",
    "daran § 5 Ziff. 2",
    "dann § 5 Ziff. 2",
    "denen § 5 Ziff. 2",
    "außen § 5 Ziff. 2",
    "draußen § 5 Ziff. 2",
    "allein § 5 Ziff. 2",
    "sein § 5 Ziff. 1",
    "am praktischsten § 4 Ziff. 4 lit. b",
    "sein § 4 Ziff. 1 lit. c",
    "bisschen § 4 Ziff. 1 lit. b",
    "nun § 3 Ziff. 1 lit. a",
    "besten § 2 Ziff. 6",
    "zittrig § 2 Ziff. 5",
    "gleichaltrig § 2 Ziff. 5",
    "starr § 2 Ziff. 6",
    "finster § 2 Ziff. 6",
    "gestrige § 2 Ziff. 6",
    "trotz § 3 Ziff. 1 lit. a",
    "loyal § 3 Ziff. 1 lit. a",
    "bayerisch § 3 Ziff. 1 lit. a",
    "stündlich § 3 Ziff. 1 lit. a",
    "gebräuchlich § 3 Ziff. 1 lit. a",
    "milchig § 3 Ziff. 1 lit. c",
    "billig § 3 Ziff. 1 lit. c",
    "heilig § 3 Ziff. 1 lit. c",
    "kühler § 3 Ziff. 1 lit. c",
    "schulisch § 3 Ziff. 1 lit. c",
    "nie § 3 Ziff. 2",
    "naiv § 3 Ziff. 2",
    "böig § 3 Ziff. 2",
    "neu § 3 Ziff. 2",
    "sächsisch § 4 Ziff. 1 lit. a",
    "schwierig § 4 Ziff. 1 lit. a",
    "spritzig § 4 Ziff. 1 lit. a",
    "sumpfig § 4 Ziff. 1 lit. a",
    "besser § 4 Ziff. 1 lit. b",
    "hässlich § 4 Ziff. 1 lit. b",
    "mäßig § 4 Ziff. 1 lit. b",
    "klassisch § 4 Ziff. 1 lit. b",
    "passiv § 4 Ziff. 1 lit. b",
    "solo § 4 Ziff. 1 lit. c",
    "persönlich § 4 Ziff. 1 lit. c",
    "unlöslich § 4 Ziff. 1 lit. c",
    "rosa § 4 Ziff. 1 lit. c",
    "seine § 4 Ziff. 1 lit. c",
    "neulich § 4 Ziff. 2",
    "ehelich § 4 Ziff. 2",
    "wehe § 4 Ziff. 3",
    "einheitlich § 4 Ziff. 3",
    "verantwortlich § 4 Ziff. 3",
    "heraus § 4 Ziff. 3",
    "eins § 4 Ziff. 4 lit. b",
    "stets § 4 Ziff. 4 lit. b",
    "vorwärts § 4 Ziff. 4 lit. b",
    "sportlich § 4 Ziff. 5",
    "geradeaus § 4 Ziff. 6",
    "geradeso § 4 Ziff. 6",
    "real § 4 Ziff. 6",
    "überseeisch § 4 Ziff. 6",
    "wieso § 4 Ziff. 6",
    "städtisch § 4 Ziff. 6",
    "desto § 4 Ziff. 6",
    "weitab § 4 Ziff. 6",
    "weitaus § 4 Ziff. 6",
    "sonach § 4 Ziff. 7",
    "absurd § 5 Ziff. 1",
    "alsobald § 5 Ziff. 2",
    "anders § 5 Ziff. 2",
    "anderthalb § 5 Ziff. 2",
    "gegeneinander § 5 Ziff. 2",
    "bislang § 5 Ziff. 2",
    "dasselbe § 5 Ziff. 2",
    "demgemäß § 5 Ziff. 2",
    "außerdem § 5 Ziff. 2",
    "derselbe § 5 Ziff. 2",
    "indes § 5 Ziff. 2",
    "ins § 5 Ziff. 2",
    "unterdes § 5 Ziff. 2",
    "unters § 5 Ziff. 2",
    "ostdeutsch § 5 Ziff. 2",
    "ostisch § 5 Ziff. 2",
    "diesjährig § 5 Ziff. 2",
    "durchs § 5 Ziff. 2",
    "durchaus § 5 Ziff. 2",
    "seiner § 5 Ziff. 2",
    "seines § 5 Ziff. 2",
    "meine, ich § 5 Ziff. 2",
    "kleine § 5 Ziff. 2",
    "fürs Erste § 5 Ziff. 2",
    "nämlich § 5 Ziff. 2",
    "hoffentlich § 5 Ziff. 2",
    "misslich § 5 Ziff. 2",
    "niederste § 5 Ziff. 2",
    "nochmals § 5 Ziff. 2",
    "hinterrücks § 5 Ziff. 2",
    "selbstverständlich § 5 Ziff. 2",
    "selbständig § 5 Ziff. 2",
    "sich's § 5 Ziff. 2",
    "sicher § 5 Ziff. 2",
    "genauso § 5 Ziff. 2",
    "sonderbarste § 5 Ziff. 2",
    "übers § 5 Ziff. 2",
    "überaus § 5 Ziff. 2",
    "überdies § 5 Ziff. 2",
    "übrigens § 5 Ziff. 2",
    "hinüber § 5 Ziff. 2",
    "unsereiner § 5 Ziff. 2",
    "völlig § 5 Ziff. 2",
    "widrig § 5 Ziff. 2",
    "widerwillig § 5 Ziff. 2",
    "wohlwollend § 5 Ziff. 2",
    "wir's § 5 Ziff. 2",
    "woraus § 5 Ziff. 2",
    "hinzu § 5 Ziff. 2",
    "unerreichbar § 5 Ziff. 3 lit. a",
    "unmittelbar § 5 Ziff. 3 lit. a",
    "unzertrennlich § 5 Ziff. 3 lit. a",
    "unordentlich § 5 Ziff. 3 lit. a",
    "zuvor § 5 Ziff. 3 lit. a",
    "unzusammenhängend § 5 Ziff. 3 lit. c",
    "unzurücknehmbar § 5 Ziff. 3 lit. c",
    "unempfindlich § 6 Ziff. 1",
    "unorganisch § 6 Ziff. 1",
    "unartig § 6 Ziff. 1",
    "uneigennützig § 6 Ziff. 1",
    "unausführbar § 6 Ziff. 1",
    "unumstößlich § 6 Ziff. 1",
    "duftend § 6 Ziff. 2",
    "fertig § 6 Ziff. 2",
    "lustig § 6 Ziff. 2",
    "günstigste § 6 Ziff. 2",
    "anderweitig § 6 Ziff. 2",
    "bzw. § 6 Ziff. 3",
    "dgl. § 6 Ziff. 3",
    "einschl. § 6 Ziff. 3",
    "e. V. § 6 Ziff. 3",
    "evtl. § 6 Ziff. 3",
    "hl. § 6 Ziff. 3",
    "kg § 6 Ziff. 3",
    "sog. § 6 Ziff. 3",
    "z. B. § 6 Ziff. 3",
    "dennoch § 7 Ziff. 1",
    "grausam § 7 Ziff. 1",
    "heutzutage § 7 Ziff. 1",
    "ansehnlich § 7 Ziff. 1",
    "beinahe § 7 Ziff. 1",
    "allmählich § 7 Ziff. 1",
    "arbeitsam § 7 Ziff. 2",
    "langsam § 7 Ziff. 2",
    "armselig § 7 Ziff. 2",
    "sparsam § 7 Ziff. 2",
    "geruchlos § 7 Ziff. 4",
    "fortlaufend § 7 Ziff. 4",
    "alldeutsch § 7 Ziff. 5",
    "altdeutsch § 7 Ziff. 5",
    "hintereinander § 7 Ziff. 5",
    "hinterlistig § 7 Ziff. 5",
    "weitgehend § 7 Ziff. 5",
    "weitläufig § 7 Ziff. 5",
    "marktschreierisch § 7 Ziff. 5",
    "irgendwo § 7 Ziff. 6",
    "großzügig § 7 Ziff. 6",
    "diesmal § 7 Ziff. 6",
    "widrigenfalls § 7 Ziff. 6",
    "nunmehr § 7 Ziff. 6",
    "außerordentlich § 7 Ziff. 6",
    "ringsum § 7 Ziff. 6",
    "polizeiwidrig § 7 Ziff. 7",
    "dreiarmig § 7 Ziff. 7",
    "solange § 7 Ziff. 8",
    "sowohl § 7 Ziff. 8",
    "soviel § 7 Ziff. 8",
    "bisher § 7 Ziff. 8",
    "dementsprechend § 7 Ziff. 8",
    "demgegenüber § 7 Ziff. 8",
    "deshalb § 7 Ziff. 8",
    "indem § 7 Ziff. 8",
    "zudem § 7 Ziff. 8",
    "alledem, trotz § 7 Ziff. 8",
    "allem, trotz § 7 Ziff. 8",
    "fröhlich § 8 Ziff. 1",
    "heller § 8 Ziff. 2",
    "irrig § 8 Ziff. 2",
    "letzter § 8 Ziff. 2",
    "ihm § 8 Ziff. 3 lit. e",
    "im § 8 Ziff. 3 lit. e",
    "drauf § 8 Ziff. 4",
    "draus § 8 Ziff. 4",
    "drüber § 8 Ziff. 4",
    "drunter § 8 Ziff. 4",
    "nichtig § 8 Ziff. 4",
    "haftende § 8 Ziff. 4",
    "o § 8 Ziff. 4",
    "generell § 9 Ziff. 2",
    "akustisch § 9 Ziff. 3",
    "sozialistisch § 9 Ziff. 3",
    "aktiv § 9 Ziff. 3",
    "parteiisch § 9 Ziff. 3",
    "sentimental § 9 Ziff. 3",
    "respektlos § 9 Ziff. 3",
    "taktvoll § 9 Ziff. 3",
    "elektronisch § 9 Ziff. 3",
    "extra § 9 Ziff. 3",
]

def make_poetry():
    """Print phrase of 3 random SU words and where to find them."""
    random.shuffle(nouns)
    random.shuffle(verbs)
    random.shuffle(pradvectives)
    noun = nouns[0].split("§")
    verb = verbs[0].split("§")
    pradvective = pradvectives[0].split("§")
    print(noun[0] + pradvective[0] + verb[0][:-1] + ".", 
          "(§" + noun[1] + ", §" + pradvective[1] + ", §" + verb[1] + ")",
          end = " "
    )

print("\nFür neue Phrase ENTER drücken, beliebige Eingabe zum Beenden.\n")
motivated = True
while motivated:
    motivated = False
    make_poetry()
    if input() == "":
        motivated = True
    else:
        raise SystemExit
